/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as berryBerryImport } from './routes/(berry)/berry'
import { Route as BerryFirmnessIndexImport } from './routes/berry_/firmness.index'
import { Route as berryBerryIndexImport } from './routes/(berry)/berry.index'
import { Route as BerryFirmnessFirmnessIdImport } from './routes/berry_/firmness.$firmnessId'
import { Route as berryBerryBerryIdImport } from './routes/(berry)/berry.$berryId'
import { Route as BerryflavorFlavorIndexImport } from './routes/berry_/(flavor)/flavor.index'
import { Route as BerryFirmnessFirmnessIdModalImport } from './routes/berry_/firmness.$firmnessId_.modal'
import { Route as BerryflavorFlavorFlavorIdImport } from './routes/berry_/(flavor)/flavor.$flavorId'
import { Route as BerryflavorFlavorFlavorIdModalImport } from './routes/berry_/(flavor)/flavor.$flavorId_.modal'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const berryBerryRoute = berryBerryImport.update({
  path: '/berry',
  getParentRoute: () => rootRoute,
} as any)

const BerryFirmnessIndexRoute = BerryFirmnessIndexImport.update({
  path: '/berry/firmness/',
  getParentRoute: () => rootRoute,
} as any)

const berryBerryIndexRoute = berryBerryIndexImport.update({
  path: '/',
  getParentRoute: () => berryBerryRoute,
} as any)

const BerryFirmnessFirmnessIdRoute = BerryFirmnessFirmnessIdImport.update({
  path: '/berry/firmness/$firmnessId',
  getParentRoute: () => rootRoute,
} as any)

const berryBerryBerryIdRoute = berryBerryBerryIdImport.update({
  path: '/$berryId',
  getParentRoute: () => berryBerryRoute,
} as any)

const BerryflavorFlavorIndexRoute = BerryflavorFlavorIndexImport.update({
  path: '/berry/flavor/',
  getParentRoute: () => rootRoute,
} as any)

const BerryFirmnessFirmnessIdModalRoute =
  BerryFirmnessFirmnessIdModalImport.update({
    path: '/berry/firmness/$firmnessId/modal',
    getParentRoute: () => rootRoute,
  } as any)

const BerryflavorFlavorFlavorIdRoute = BerryflavorFlavorFlavorIdImport.update({
  path: '/berry/flavor/$flavorId',
  getParentRoute: () => rootRoute,
} as any)

const BerryflavorFlavorFlavorIdModalRoute =
  BerryflavorFlavorFlavorIdModalImport.update({
    path: '/berry/flavor/$flavorId/modal',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(berry)/berry': {
      id: '/berry'
      path: '/berry'
      fullPath: '/berry'
      preLoaderRoute: typeof berryBerryImport
      parentRoute: typeof rootRoute
    }
    '/(berry)/berry/$berryId': {
      id: '/berry/$berryId'
      path: '/$berryId'
      fullPath: '/berry/$berryId'
      preLoaderRoute: typeof berryBerryBerryIdImport
      parentRoute: typeof berryBerryImport
    }
    '/berry/firmness/$firmnessId': {
      id: '/berry/firmness/$firmnessId'
      path: '/berry/firmness/$firmnessId'
      fullPath: '/berry/firmness/$firmnessId'
      preLoaderRoute: typeof BerryFirmnessFirmnessIdImport
      parentRoute: typeof rootRoute
    }
    '/(berry)/berry/': {
      id: '/berry/'
      path: '/'
      fullPath: '/berry/'
      preLoaderRoute: typeof berryBerryIndexImport
      parentRoute: typeof berryBerryImport
    }
    '/berry/firmness/': {
      id: '/berry/firmness/'
      path: '/berry/firmness'
      fullPath: '/berry/firmness'
      preLoaderRoute: typeof BerryFirmnessIndexImport
      parentRoute: typeof rootRoute
    }
    '/berry/(flavor)/flavor/$flavorId': {
      id: '/berry/flavor/$flavorId'
      path: '/berry/flavor/$flavorId'
      fullPath: '/berry/flavor/$flavorId'
      preLoaderRoute: typeof BerryflavorFlavorFlavorIdImport
      parentRoute: typeof rootRoute
    }
    '/berry/firmness/$firmnessId/modal': {
      id: '/berry/firmness/$firmnessId/modal'
      path: '/berry/firmness/$firmnessId/modal'
      fullPath: '/berry/firmness/$firmnessId/modal'
      preLoaderRoute: typeof BerryFirmnessFirmnessIdModalImport
      parentRoute: typeof rootRoute
    }
    '/berry/(flavor)/flavor/': {
      id: '/berry/flavor/'
      path: '/berry/flavor'
      fullPath: '/berry/flavor'
      preLoaderRoute: typeof BerryflavorFlavorIndexImport
      parentRoute: typeof rootRoute
    }
    '/berry/(flavor)/flavor/$flavorId/modal': {
      id: '/berry/flavor/$flavorId/modal'
      path: '/berry/flavor/$flavorId/modal'
      fullPath: '/berry/flavor/$flavorId/modal'
      preLoaderRoute: typeof BerryflavorFlavorFlavorIdModalImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface berryBerryRouteChildren {
  berryBerryBerryIdRoute: typeof berryBerryBerryIdRoute
  berryBerryIndexRoute: typeof berryBerryIndexRoute
}

const berryBerryRouteChildren: berryBerryRouteChildren = {
  berryBerryBerryIdRoute: berryBerryBerryIdRoute,
  berryBerryIndexRoute: berryBerryIndexRoute,
}

const berryBerryRouteWithChildren = berryBerryRoute._addFileChildren(
  berryBerryRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/berry': typeof berryBerryRouteWithChildren
  '/berry/$berryId': typeof berryBerryBerryIdRoute
  '/berry/firmness/$firmnessId': typeof BerryFirmnessFirmnessIdRoute
  '/berry/': typeof berryBerryIndexRoute
  '/berry/firmness': typeof BerryFirmnessIndexRoute
  '/berry/flavor/$flavorId': typeof BerryflavorFlavorFlavorIdRoute
  '/berry/firmness/$firmnessId/modal': typeof BerryFirmnessFirmnessIdModalRoute
  '/berry/flavor': typeof BerryflavorFlavorIndexRoute
  '/berry/flavor/$flavorId/modal': typeof BerryflavorFlavorFlavorIdModalRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/berry/$berryId': typeof berryBerryBerryIdRoute
  '/berry/firmness/$firmnessId': typeof BerryFirmnessFirmnessIdRoute
  '/berry': typeof berryBerryIndexRoute
  '/berry/firmness': typeof BerryFirmnessIndexRoute
  '/berry/flavor/$flavorId': typeof BerryflavorFlavorFlavorIdRoute
  '/berry/firmness/$firmnessId/modal': typeof BerryFirmnessFirmnessIdModalRoute
  '/berry/flavor': typeof BerryflavorFlavorIndexRoute
  '/berry/flavor/$flavorId/modal': typeof BerryflavorFlavorFlavorIdModalRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/berry': typeof berryBerryRouteWithChildren
  '/berry/$berryId': typeof berryBerryBerryIdRoute
  '/berry/firmness/$firmnessId': typeof BerryFirmnessFirmnessIdRoute
  '/berry/': typeof berryBerryIndexRoute
  '/berry/firmness/': typeof BerryFirmnessIndexRoute
  '/berry/flavor/$flavorId': typeof BerryflavorFlavorFlavorIdRoute
  '/berry/firmness/$firmnessId/modal': typeof BerryFirmnessFirmnessIdModalRoute
  '/berry/flavor/': typeof BerryflavorFlavorIndexRoute
  '/berry/flavor/$flavorId/modal': typeof BerryflavorFlavorFlavorIdModalRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/berry'
    | '/berry/$berryId'
    | '/berry/firmness/$firmnessId'
    | '/berry/'
    | '/berry/firmness'
    | '/berry/flavor/$flavorId'
    | '/berry/firmness/$firmnessId/modal'
    | '/berry/flavor'
    | '/berry/flavor/$flavorId/modal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/berry/$berryId'
    | '/berry/firmness/$firmnessId'
    | '/berry'
    | '/berry/firmness'
    | '/berry/flavor/$flavorId'
    | '/berry/firmness/$firmnessId/modal'
    | '/berry/flavor'
    | '/berry/flavor/$flavorId/modal'
  id:
    | '__root__'
    | '/'
    | '/berry'
    | '/berry/$berryId'
    | '/berry/firmness/$firmnessId'
    | '/berry/'
    | '/berry/firmness/'
    | '/berry/flavor/$flavorId'
    | '/berry/firmness/$firmnessId/modal'
    | '/berry/flavor/'
    | '/berry/flavor/$flavorId/modal'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  berryBerryRoute: typeof berryBerryRouteWithChildren
  BerryFirmnessFirmnessIdRoute: typeof BerryFirmnessFirmnessIdRoute
  BerryFirmnessIndexRoute: typeof BerryFirmnessIndexRoute
  BerryflavorFlavorFlavorIdRoute: typeof BerryflavorFlavorFlavorIdRoute
  BerryFirmnessFirmnessIdModalRoute: typeof BerryFirmnessFirmnessIdModalRoute
  BerryflavorFlavorIndexRoute: typeof BerryflavorFlavorIndexRoute
  BerryflavorFlavorFlavorIdModalRoute: typeof BerryflavorFlavorFlavorIdModalRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  berryBerryRoute: berryBerryRouteWithChildren,
  BerryFirmnessFirmnessIdRoute: BerryFirmnessFirmnessIdRoute,
  BerryFirmnessIndexRoute: BerryFirmnessIndexRoute,
  BerryflavorFlavorFlavorIdRoute: BerryflavorFlavorFlavorIdRoute,
  BerryFirmnessFirmnessIdModalRoute: BerryFirmnessFirmnessIdModalRoute,
  BerryflavorFlavorIndexRoute: BerryflavorFlavorIndexRoute,
  BerryflavorFlavorFlavorIdModalRoute: BerryflavorFlavorFlavorIdModalRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/berry",
        "/berry/firmness/$firmnessId",
        "/berry/firmness/",
        "/berry/flavor/$flavorId",
        "/berry/firmness/$firmnessId/modal",
        "/berry/flavor/",
        "/berry/flavor/$flavorId/modal"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/berry": {
      "filePath": "(berry)/berry.tsx",
      "children": [
        "/berry/$berryId",
        "/berry/"
      ]
    },
    "/berry/$berryId": {
      "filePath": "(berry)/berry.$berryId.tsx",
      "parent": "/berry"
    },
    "/berry/firmness/$firmnessId": {
      "filePath": "berry_/firmness.$firmnessId.tsx"
    },
    "/berry/": {
      "filePath": "(berry)/berry.index.tsx",
      "parent": "/berry"
    },
    "/berry/firmness/": {
      "filePath": "berry_/firmness.index.tsx"
    },
    "/berry/flavor/$flavorId": {
      "filePath": "berry_/(flavor)/flavor.$flavorId.tsx"
    },
    "/berry/firmness/$firmnessId/modal": {
      "filePath": "berry_/firmness.$firmnessId_.modal.tsx"
    },
    "/berry/flavor/": {
      "filePath": "berry_/(flavor)/flavor.index.tsx"
    },
    "/berry/flavor/$flavorId/modal": {
      "filePath": "berry_/(flavor)/flavor.$flavorId_.modal.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
