name: CI / React

on:
    push:

env:
    HUSKY: 0

jobs:
  commit-checks:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    name: pre-commit-js
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v4.0.2
        with:
            node-version-file: ".nvmrc"
            cache: "npm"
            check-latest: true
            cache-dependency-path: './package-lock.json'

      - name: Install dependencies
        run: npm install --include dev --no-audit

      - name: Run lint
        run: |
            if [ ! -f .env.local ]; then 
                cp .env.template .env.local;
            fi
            npm run lint --quiet

      - name: Run type checks
        run: npm run lint:types

      - name: Run tests
        run: npm run test

      - name: Comment on Summary if Failure
        if: ${{ failure() }}
        run: |
            echo "Lint checks failed. Please review and fix the issues." | tee -a ${GITHUB_STEP_SUMMARY}
